name: Supabase Project Pinger

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main  # Run on push to main branch

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run ping
        run: |
          echo "Starting ping at $(date)"
          echo "GitHub Actions run ID: $GITHUB_RUN_ID"
          echo "GitHub Actions run number: $GITHUB_RUN_NUMBER"
          node ping.js
          echo "Completed ping at $(date)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 